"""
Generate synthetic risk features for DeepRT-SOTA v2.

Creates negative_risk_score and spike_risk_score based on simple rules.
This is a temporary solution until real risk features are available.
"""
import numpy as np
import pandas as pd
from pathlib import Path

import logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)


def generate_synthetic_risk_features(df: pd.DataFrame) -> pd.DataFrame:
    """Generate synthetic risk features.
    
    Rules:
    - negative_risk_score: 1 if rt_actual < 0, else 0 (simplified)
    - spike_risk_score: 1 if rt_actual > 500, else 0 (simplified)
    
    Note: These are VERY simplified. Real risk features should be generated by risk modules.
    """
    df = df.copy()
    
    # Negative risk score (simplified: based on rt_actual)
    df['negative_risk_score'] = (df['rt_actual'] < 0).astype(float)
    
    # Spike risk score (simplified: based on rt_actual)
    df['spike_risk_score'] = (df['rt_actual'] > 500).astype(float)
    
    # Add some noise to make it more realistic
    np.random.seed(42)
    df['negative_risk_score'] = df['negative_risk_score'] * 0.8 + np.random.rand(len(df)) * 0.2
    df['spike_risk_score'] = df['spike_risk_score'] * 0.8 + np.random.rand(len(df)) * 0.2
    
    logger.info(f"Generated synthetic risk features for {len(df)} rows")
    logger.info(f"  negative_risk_score: mean={df['negative_risk_score'].mean():.4f}, max={df['negative_risk_score'].max():.4f}")
    logger.info(f"  spike_risk_score: mean={df['spike_risk_score'].mean():.4f}, max={df['spike_risk_score'].max():.4f}")
    
    return df


def main():
    """Generate synthetic risk features and save to CSV."""
    logger.info("Generating synthetic risk features...")
    
    # Load data
    data_path = 'D:/作业/大创_挑战杯_互联网/大学生创新创业计划/大创实现/其他资料/electricity_forecast_model2.0_exp/data/shandong_pmos_hourly.csv'
    df = pd.read_csv(data_path, encoding='gbk')
    df = df.rename(columns={
        '时刻': 'ds',
        '日前电价': 'da_anchor',
        '实时电价': 'rt_actual',
    })
    df['ds'] = pd.to_datetime(df['ds'])
    
    # Generate synthetic risk features
    df_with_risk = generate_synthetic_risk_features(df)
    
    # Save to CSV (for use in training)
    out_path = Path('artifacts/deep_rt_sota/synthetic_risk_features.csv')
    out_path.parent.mkdir(parents=True, exist_ok=True)
    
    df_with_risk[['ds', 'rt_actual', 'negative_risk_score', 'spike_risk_score']].to_csv(out_path, index=False, encoding='utf-8')
    
    logger.info(f"Synthetic risk features saved to {out_path}")
    logger.info("\nYou can now use these risk features in training by setting risk_features=True")


if __name__ == '__main__':
    main()
